// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd-TH4JGgtcyBPoHMsfoY8U56Fqqr8DhE',
    appId: '1:1022545947782:web:7f4b0e7c40a8943043b507',
    messagingSenderId: '1022545947782',
    projectId: 'saklolo-76516',
    authDomain: 'saklolo-76516.firebaseapp.com',
    storageBucket: 'saklolo-76516.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf7SF6b0VEUQ5WTuQCSIMIbwNagnxyjII',
    appId: '1:1022545947782:android:9b08c829a0e1fe8e43b507',
    messagingSenderId: '1022545947782',
    projectId: 'saklolo-76516',
    storageBucket: 'saklolo-76516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmlsp1jSd9znz4rQ-3Rbhc7jBCf8mV9xg',
    appId: '1:1022545947782:ios:52ac75baa287d43143b507',
    messagingSenderId: '1022545947782',
    projectId: 'saklolo-76516',
    storageBucket: 'saklolo-76516.appspot.com',
    iosBundleId: 'com.example.saklolo2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmlsp1jSd9znz4rQ-3Rbhc7jBCf8mV9xg',
    appId: '1:1022545947782:ios:52ac75baa287d43143b507',
    messagingSenderId: '1022545947782',
    projectId: 'saklolo-76516',
    storageBucket: 'saklolo-76516.appspot.com',
    iosBundleId: 'com.example.saklolo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd-TH4JGgtcyBPoHMsfoY8U56Fqqr8DhE',
    appId: '1:1022545947782:web:444ce0e0de822a6043b507',
    messagingSenderId: '1022545947782',
    projectId: 'saklolo-76516',
    authDomain: 'saklolo-76516.firebaseapp.com',
    storageBucket: 'saklolo-76516.appspot.com',
  );
}
